# Generated by Django 3.1.3 on 2020-12-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
